config/routes.rb
BetterChat::Application.routes.draw do
  
  root 'home#index'

  match '/new_message' => 'messages#new_message', via: [:post]

end

app/models/message.rb
class Message
  include Mongoid::Document

  field :content
  field :created_at, type: Time
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def new_message
    if !params[:nickname] or params[:nickname].strip.empty?
      @nick = 'Anonymous'
    else
      @nick = params[:nickname].strip
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.haml
%h1
  %del
    Better
  %em
    Still Lame
  Chat!
%hr

%h3 Chat box:
.row
  .col-xs-6.chat-box#chat-box
  .col-xs-1
  .col-xs-4{style: 'padding: 0'}
    = form_tag new_message_path, method: 'post', remote: true do
      = label_tag 'Nickname'
      %br
      = text_field_tag :nickname, nil, class: 'form-control', placeholder: 'Anonymous'
      %br
      = label_tag 'Message'
      %br
      = text_area_tag :content, nil, class: 'form-control', style: 'resize: none; height: 100px', id: 'msg-input'
      %br
      = submit_tag 'Send', class: 'btn btn-primary'

= subscribe_to '/messages/new'

app/views/layouts/application.html.haml
!!!
%head
  %title Chat
  = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
  = javascript_include_tag "application", "data-turbolinks-track" => true
  = csrf_meta_tags

  %link{:href=>"//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css", :rel=>"stylesheet"}
  %script{:src=>"//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"}
  %link{:href=>"//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css", :rel=>"stylesheet"}
  %link{:href=>'http://fonts.googleapis.com/css?family=Open+Sans:400,300,700', :rel=>'stylesheet'}
  

%body
  .container
    = yield

app/views/messages/_message.html.haml
%strong
  Message at
  = time
  by
  = nick
%br
%p= content

app/views/messages/new_message.js.erb
<% publish_to '/messages/new' do %>
  var render = "<%= j(render partial: 'messages/message', locals: {time: Time.now, content: params[:content], nick: @nick}) %>";
  $("#chat-box").append(render);
<% end %>
$("#msg-input").val('');